// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-shop-v2/internal/dao/internal"
)

// internalEventeECardExtendDao is internal type for wrapping internal DAO implements.
type internalEventeECardExtendDao = *internal.EventeECardExtendDao

// eventeECardExtendDao is the data access object for table evente_e_card_extend.
// You can define custom methods on it to extend its functionality as you wish.
type eventeECardExtendDao struct {
	internalEventeECardExtendDao
}

var (
	// EventeECardExtend is globally public accessible object for table evente_e_card_extend operations.
	EventeECardExtend = eventeECardExtendDao{
		internal.NewEventeECardExtendDao(),
	}
)

// Fill with you ideas below.
