// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-shop-v2/internal/dao/internal"
)

// internalEventeECardDao is internal type for wrapping internal DAO implements.
type internalEventeECardDao = *internal.EventeECardDao

// eventeECardDao is the data access object for table evente_e_card.
// You can define custom methods on it to extend its functionality as you wish.
type eventeECardDao struct {
	internalEventeECardDao
}

var (
	// EventeECard is globally public accessible object for table evente_e_card operations.
	EventeECard = eventeECardDao{
		internal.NewEventeECardDao(),
	}
)

// Fill with you ideas below.
