// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EventeECardExtend is the golang structure for table evente_e_card_extend.
type EventeECardExtend struct {
	Id           uint        `json:"id"           description:""`
	OrgId        int         `json:"orgId"        description:"主办id"`
	CardId       int         `json:"cardId"       description:"E通卡id"`
	EventeId     int         `json:"eventeId"     description:"活动id"`
	ScreeningsId int         `json:"screeningsId" description:"场次id"`
	PriceId      string      `json:"priceId"      description:"票品ID集合 如 :9988,2235,6667"`
	CreateDate   *gtime.Time `json:"createDate"   description:"创建时间"`
	UpdateDate   *gtime.Time `json:"updateDate"   description:"修改时间"`
}
